/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCashflowContractArgs } from "./CreateCashflowContractArgs";
import { UpdateCashflowContractArgs } from "./UpdateCashflowContractArgs";
import { DeleteCashflowContractArgs } from "./DeleteCashflowContractArgs";
import { CashflowContractFindManyArgs } from "./CashflowContractFindManyArgs";
import { CashflowContractFindUniqueArgs } from "./CashflowContractFindUniqueArgs";
import { CashflowContract } from "./CashflowContract";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { CashflowContractService } from "../cashflowContract.service";

@graphql.Resolver(() => CashflowContract)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CashflowContractResolverBase {
  constructor(
    protected readonly service: CashflowContractService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async _cashflowContractsMeta(
    @graphql.Args() args: CashflowContractFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CashflowContract])
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async cashflowContracts(
    @graphql.Args() args: CashflowContractFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CashflowContract",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CashflowContract, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "own",
  })
  async cashflowContract(
    @graphql.Args() args: CashflowContractFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CashflowContract",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CashflowContract)
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "create",
    possession: "any",
  })
  async createCashflowContract(
    @graphql.Args() args: CreateCashflowContractArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CashflowContract",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CashflowContract"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        manager: args.data.manager
          ? {
              connect: args.data.manager,
            }
          : undefined,

        series: args.data.series
          ? {
              connect: args.data.series,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CashflowContract)
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "update",
    possession: "any",
  })
  async updateCashflowContract(
    @graphql.Args() args: UpdateCashflowContractArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CashflowContract",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CashflowContract"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          manager: args.data.manager
            ? {
                connect: args.data.manager,
              }
            : undefined,

          series: args.data.series
            ? {
                connect: args.data.series,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CashflowContract)
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "delete",
    possession: "any",
  })
  async deleteCashflowContract(
    @graphql.Args() args: DeleteCashflowContractArgs
  ): Promise<CashflowContract | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CashflowContract])
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async contracts(
    @graphql.Parent() parent: CashflowContract,
    @graphql.Args() args: CashflowContractFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CashflowContract",
    });
    const results = await this.service.findContracts(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: CashflowContract,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async manager(
    @graphql.Parent() parent: CashflowContract,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getManager(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => CashflowContract, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CashflowContract",
    action: "read",
    possession: "any",
  })
  async series(
    @graphql.Parent() parent: CashflowContract,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CashflowContract | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CashflowContract",
    });
    const result = await this.service.getSeries(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
