/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, CashflowContract, User } from "@prisma/client";

export class CashflowContractServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CashflowContractFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractFindManyArgs>
  ): Promise<number> {
    return this.prisma.cashflowContract.count(args);
  }

  async findMany<T extends Prisma.CashflowContractFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractFindManyArgs>
  ): Promise<CashflowContract[]> {
    return this.prisma.cashflowContract.findMany(args);
  }
  async findOne<T extends Prisma.CashflowContractFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractFindUniqueArgs>
  ): Promise<CashflowContract | null> {
    return this.prisma.cashflowContract.findUnique(args);
  }
  async create<T extends Prisma.CashflowContractCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractCreateArgs>
  ): Promise<CashflowContract> {
    return this.prisma.cashflowContract.create<T>(args);
  }
  async update<T extends Prisma.CashflowContractUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractUpdateArgs>
  ): Promise<CashflowContract> {
    return this.prisma.cashflowContract.update<T>(args);
  }
  async delete<T extends Prisma.CashflowContractDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CashflowContractDeleteArgs>
  ): Promise<CashflowContract> {
    return this.prisma.cashflowContract.delete(args);
  }

  async findCashflowContracts(
    parentId: string,
    args: Prisma.CashflowContractFindManyArgs
  ): Promise<CashflowContract[]> {
    return this.prisma.cashflowContract
      .findUnique({
        where: { id: parentId },
      })
      .cashflowContracts(args);
  }

  async findUsers(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.cashflowContract
      .findUnique({
        where: { id: parentId },
      })
      .users(args);
  }

  async getManager(parentId: string): Promise<User | null> {
    return this.prisma.cashflowContract
      .findUnique({
        where: { id: parentId },
      })
      .manager();
  }

  async getSeries(parentId: string): Promise<CashflowContract | null> {
    return this.prisma.cashflowContract
      .findUnique({
        where: { id: parentId },
      })
      .series();
  }
}
