/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExpenseCreateNestedManyWithoutUsersInput } from "./ExpenseCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CashflowContractCreateNestedManyWithoutUsersInput } from "./CashflowContractCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => ExpenseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  approvedExpenses?: ExpenseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CashflowContractCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CashflowContractCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CashflowContractCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  cashflowContract?: CashflowContractCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CashflowContractCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CashflowContractCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CashflowContractCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  cashflowContractsManager?: CashflowContractCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ExpenseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  expenses?: ExpenseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
